"""AddEmbeddingColumnInMovies

Revision ID: 34e4ac129cdd
Revises: c2f23826fdc5
Create Date: 2025-10-10 21:27:15.479392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '34e4ac129cdd'
down_revision: Union[str, None] = 'c2f23826fdc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'embedding')
    # ### end Alembic commands ###
